parameters:
#    ydle_user.example.class: Ydle\UserBundle\Example

services:
#    ydle_user.example:
#        class: %ydle_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
